
"use client";
import React from "react";
import CustomTable from "@/components/Tables/CustomTable";
import { Row, Col, Card, CardBody } from "reactstrap";
import Image from "next/image";
import Link from "next/link";


// Import Components
import MyChart from "@/components/MyChart/MyChart"
export default function Dashboard() {
  // Top Boxes Items
  const TopItems = [
    {
      icon: "/itam/images/box_plus.png",
      name: "Assets",
      count: 643,
    },
    {
      icon: "/itam/images/file_plus.png",
      name: "Maintenance",
      count: 53,
    },
    {
      icon: "/itam/images/ticket.png",
      name: "Tickets",
      count: 64,
    },
    {
      icon: "/itam/images/user.png",
      name: "Users",
      count: 495,
    },
  ];

   // ALL Tickets Table Head Data
   const thead = [
    {
      key: "added_on",
      label: "Added On",
    },
    {
      key: "generated_by",
      label: "Generated By",
    },
    {
      key: "description",
      label: "Description",
    },
    {
      key: "type",
      label: "Type",
    },
    {
      key: "status",
      label: "Status",
    },
    {
      key: "assigned",
      label: "Assigned",
    },
    {
      key: "action",
      label: "Action",
    },
  ];

  // All Tickets Body Data
  const tbody = [
    {
      added_on: (
        <div className="">
          <p className="white big m-0 p-0">Jan 19,2022</p>
          <p className="light small m-0 p-0">3:45 pm</p>
        </div>
      ),
      generated_by: (
        <div className="image_Box">
          <Image loading="lazy"width={20} height={20} src="/itam/images/user/user-01.png" alt="" />
          <div>
            <p className="white big m-0 p-0">Dianne Russell</p>
            <p className="small m-0 p-0 underline">Macbook 13” 2024</p>
          </div>
        </div>
      ),
      description: (
        <div className="">
          <p className="light big m-0 p-0">Ticket Subject</p>
          <p className="light small m-0 p-0">Issue explanation </p>
        </div>
      ),
      type: (
        <div className="tag_name">
          <span className="span">Complain</span>
        </div>
      ),
      status: (
        <div className="select_icon">
          <select name="" className="form-control" id="">
            <option value="">Pending</option>
            <option value="">Completed</option>
            <option value="">Canceled</option>
          </select>
          <span className="icon">
            <svg
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              stroke="#fcba03"
              strokeWidth="1"
              strokeLinecap="round"
              strokeLinejoin="miter"
            >
              <circle cx="12" cy="12" r="10"></circle>
              <polyline points="8 10 12 15 16 10"></polyline>
            </svg>
          </span>
          {/* <Select options={options} /> */}
        </div>
      ),
      assigned: (
        <div className="icon_number">
          <span className="table_icon">
            <svg
              width="16px"
              height="16px"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle
                cx="12"
                cy="6"
                r="4"
                stroke="#1C274C"
                strokeWidth="1.5"
              />
              <ellipse
                cx="12"
                cy="17"
                rx="7"
                ry="4"
                stroke="#1C274C"
                strokeWidth="1.5"
              />
            </svg>
          </span>
          <span className="count">1</span>
        </div>
      ),
      action: (
        <div>
          <Link href="#" className="table_icon">
            <svg
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M9.71069 18.2929C10.1012 18.6834 10.7344 18.6834 11.1249 18.2929L16.0123 13.4006C16.7927 12.6195 16.7924 11.3537 16.0117 10.5729L11.1213 5.68254C10.7308 5.29202 10.0976 5.29202 9.70708 5.68254C9.31655 6.07307 9.31655 6.70623 9.70708 7.09676L13.8927 11.2824C14.2833 11.6729 14.2833 12.3061 13.8927 12.6966L9.71069 16.8787C9.32016 17.2692 9.32016 17.9023 9.71069 18.2929Z"
                fill=""
              />
            </svg>
          </Link>
        </div>
      ),
    },
  ];

  return (
    <>
      {/* Dashboard Top Card Section Start */}
      <div className="top_cards">
        <Row>
          {TopItems.map((TopItems, index) => (
            <Col md="3" key={index}>
              <Card>
                <CardBody>
                  <div className="boxes">
                    <div className="icon">
                      <Image
                        width={20}
                        height={20}
                        src={TopItems.icon}
                        alt=""
                      />
                    </div>
                    <div className="content_text">
                      <p className="name mb-0 pb-0">{TopItems.name}</p>
                      <h4 className="count mb-0 pb-0">{TopItems.count}</h4>
                    </div>
                  </div>
                </CardBody>
              </Card>
            </Col>
          ))}
        </Row>
      </div>
      {/* Dashboard Top Card Section End */}

      {/* Dashboard Chart Section Start */}
      <MyChart/>
      {/* Dashboard Chart Section End */}

      {/* Dasboar Board Table Section Start */}
      <div className="custom_table mt-3">
        <Card>
          <CardBody>
            <Row>
              <Col md="12">
                <div className="table_head d-flex align-items-center justify-content-between">
                  <div className="f_col">
                    <h3 className="heading">All Tickets</h3>
                  </div>
                  <div className="filter">
                    <select name="" id="">
                      <option value="">All Type</option>
                      <option value="">Active</option>
                      <option value="">Unactive</option>
                    </select>
                    <select name="" id="">
                      <option value="">Status</option>
                      <option value="">Active</option>
                      <option value="">Unactive</option>
                    </select>
                    <div className="search_table">
                      <span className="search_icon">
                        <svg
                          viewBox="0 0 24 24"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M15.7955 15.8111L21 21M18 10.5C18 14.6421 14.6421 18 10.5 18C6.35786 18 3 14.6421 3 10.5C3 6.35786 6.35786 3 10.5 3C14.6421 3 18 6.35786 18 10.5Z"
                            stroke=""
                            strokeWidth="1"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                      </span>
                      <input
                        type=""
                        placeholder="Search"
                        className="form-control"
                      />
                    </div>
                  </div>
                </div>
                <div className="table_body">
                  <CustomTable theadName={thead} BoydData={tbody} />
                </div>
              </Col>
            </Row>
          </CardBody>
        </Card>
      </div>
      {/* Dasboar Board Table Section End */}
    </>
  );
}
